Name       = "wordpress"
Env        = "Dev"
Created_by = "Caglar"
Dept       = "IT"
ami                         = "ami-0b898040803850657"
instance_type               = "t2.micro"
key_name                    = "terraform_april"
count                       = "3"