Name       = "wordpress"
Env        = "Dev"
Created_by = "Caglar"
Dept       = "IT"
ami                         = "ami-0f283b180b89f6431"
instance_type               = "t2.micro"
key_name                    = "terraform_april"
